name: "dbt_telecom_project"
version: "1.0"
profile: "snowflake_telecom"
config-version: 2
models:
  dbt_telecom_project:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table
